Maintain Data Status of Materialized Views for Partitioned Tables.
apache/cloudberry pull request #786
Opened 2024-12-16 09:55 UTC by avamingli

## Handle of data status changes for materialized views associated with partitioned tables.

Writable operations (**INSERT, UPDATE, DELETE, COPY, TRUNCATE, CLUSTER and etc**) on a base table lead to changes in the data status of linked materialized views. For partitioned tables, changes in child partitions can impact parent and ancestor tables, necessitating updates to the relevant materialized views.
  
For example, consider a root partitioned table P0 with two child partitioned tables: P1 and P2. Each child table further has 
two sub-partitions: P1 has P1_1 and P1_2, while P2 has P2_1 and P2_2.   
![q_dynamic_table drawio](https://github.com/user-attachments/assets/c9c5e187-9030-4b52-95ec-663cf9d8912f)
If we insert rows into P1_1, the data status of both mv0 (based on P0) and mv1 (based on P1) will change, as P1_1's parent table P1 and the root table P0 now contain more rows. 
![q_dynamic_table drawio2](https://github.com/user-attachments/assets/6b0d6f01-4803-448d-a69f-d880f206307d)
Conversely, if we insert rows into P2_1, only the data status of mv2_1 (based on P2_1) and mv0 will be affected, while mv1 remains unchanged because the data in P1 has not changed.
![q_dynamic_table drawio3](https://github.com/user-attachments/assets/ed674dee-ed7f-4ce7-b5be-baccb1e55bd2)

## Propagation Direction: 
  Data status changes propagate both UP and DOWN the partition tree, except for specific DDL operations:
  * **Create Table XXX Partition Of**:
	  Indicates an insert operation on the parent table.
  * **Drop Table**:
	   Indicates a delete operation on the parent table.
  * **Alter Table ATTACH/DETACH** :
	  Attaching implies an insert, while detaching implies a delete.

Handling **TRUNCATE** and **CLUSTER**: A TRUNCATE operation on a parent table is treated as a DELETE on its child tables, affecting both the parent and its descendants. Similarly, a CLUSTER operation will transform the data status in both UP and DOWN directions. However, CLUSTER has a recognized status to indicate that the changes have been applied to the pages of the tables.

The **COPY** command indicates that data has been inserted into the table and its ancestor tables.

The **VACUUM** command indicates that data has been recognized on the table and its ancestor tables.

Authored-by: Zhang Mingli avamingli@gmail.com

Fixes #ISSUE_Number

### What does this PR do?

### Type of Change
- [ ] Bug fix (non-breaking change)
- [ ] New feature (non-breaking change)
- [ ] Breaking change (fix or feature with breaking changes)
- [ ] Documentation update

### Breaking Changes

### Test Plan

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Passed `make installcheck`
- [ ] Passed `make -C src/test installcheck-cbdb-parallel`

### Impact

**Performance:**

**User-facing changes:**

**Dependencies:**

### Checklist
- [ ] Followed [contribution guide](https://cloudberry.apache.org/contribute/code)
- [ ] Added/updated documentation
- [ ] Reviewed code for security implications
- [ ] Requested review from [cloudberry committers](https://github.com/orgs/apache/teams/cloudberry-committers)

### Additional Context

### CI Skip Instructions

---

2024-12-17 04:51 UTC, avamingli commented
Push a temp commit to debug CI failure which I could not reproduce locally. Will remote it after case fixed.

2024-12-18 03:45 UTC, avamingli commented
> Push a temp commit to debug CI failure which I could not reproduce locally. Will remove it after case fixed.

Didn't do anything and CI passed after retry.

2024-12-25 02:37 UTC, yjhjstz requested changes
LGTM

2024-12-25 04:11 UTC, yjhjstz approved these changes

2024-12-25 04:24 UTC, my-ship-it approved these changes

2024-12-25 04:25 UTC, merged